name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - lightgbm
  - optuna
  - imbalanced-learn
  - shap
  - streamlit
  - joblib
  - altair
  - ipython
  - pip
  - pip:
      - --trusted-host pypi.org
      - --trusted-host files.pythonhosted.org
      - streamlit
      - joblib
      - some-pip-package

